'-------------------------
' category
'-------------------------
' LIGHT
'-------------------------
@startuml
!theme mono
hide circle
skinparam linetype ortho
skinparam defaultFontName Arial

entity PERSON {
  * <color:#9b59b6><b>ssn</b></color> : varchar <<PK>>
  --
  * name : varchar
}

entity COMPANY {
  * <color:#9b59b6><b>tax_id</b></color> : varchar <<PK>>
  --
  * company_name : varchar
}

entity BANK {
  * <color:#9b59b6><b>routing_no</b></color> : varchar <<PK>>
  --
  * bank_name : varchar
}

entity VEHICLE_OWNER {
  * <color:#9b59b6><b>owner_id</b></color> : int <<PK (surrogate)>>
  --
  * owner_type : varchar <<CHECK: person/company/bank>>
    <color:#336791><b>person_ssn</b></color> : varchar <<FK -> PERSON>>
    <color:#336791><b>company_tax_id</b></color> : varchar <<FK -> COMPANY>>
    <color:#336791><b>bank_routing_no</b></color> : varchar <<FK -> BANK>>
  * ownership_date : date
  --
  {CHECK: exactly one FK is NOT NULL}
}

PERSON ||--o| VEHICLE_OWNER : "owner (person)"
COMPANY ||--o| VEHICLE_OWNER : "owner (company)"
BANK ||--o| VEHICLE_OWNER : "owner (bank)"
@enduml
'-------------------------
' Dark
'-------------------------
@startuml
!theme blueprint
hide circle
skinparam linetype ortho
skinparam defaultFontName Arial

entity PERSON {
  * <color:#EECBFF><b>ssn</b></color> : varchar <<PK>>
  --
  * name : varchar
}

entity COMPANY {
  * <color:#EECBFF><b>tax_id</b></color> : varchar <<PK>>
  --
  * company_name : varchar
}

entity BANK {
  * <color:#EECBFF><b>routing_no</b></color> : varchar <<PK>>
  --
  * bank_name : varchar
}

entity VEHICLE_OWNER {
  * <color:#EECBFF><b>owner_id</b></color> : int <<PK (surrogate)>>
  --
  * owner_type : varchar <<CHECK: person/company/bank>>
    <color:#E6EDF9><b>person_ssn</b></color> : varchar <<FK -> PERSON>>
    <color:#E6EDF9><b>company_tax_id</b></color> : varchar <<FK -> COMPANY>>
    <color:#E6EDF9><b>bank_routing_no</b></color> : varchar <<FK -> BANK>>
  * ownership_date : date
  --
  {CHECK: exactly one FK is NOT NULL}
}

PERSON ||--o| VEHICLE_OWNER : "owner (person)"
COMPANY ||--o| VEHICLE_OWNER : "owner (company)"
BANK ||--o| VEHICLE_OWNER : "owner (bank)"
@enduml