'-------------------------
' n-ary
'-------------------------
' LIGHT
'-------------------------
@startuml
!theme mono
hide circle
skinparam linetype ortho
skinparam defaultFontName Arial

entity PERSON {
  * <color:#9b59b6><b>person_id</b></color> : int <<PK>>
  --
  * first_name : varchar
    middle_name : varchar
  * last_name : varchar
  * date_of_birth : date
}

entity PERSON_PHONE {
  * <color:#9b59b6><b>person_id</b></color> : int <<PK, FK -> PERSON>>
  * <color:#9b59b6><b>phone_number</b></color> : varchar <<PK>>
  --
}

entity PERSON_EMAIL {
  * <color:#9b59b6><b>person_id</b></color> : int <<PK, FK -> PERSON>>
  * <color:#9b59b6><b>email_address</b></color> : varchar <<PK>>
  --
}

entity PROFESSOR {
  * <color:#9b59b6><b>person_id</b></color> : int <<PK, FK -> PERSON>>
  --
  * professor_id : varchar <<UK>>
    salary : numeric
  * hire_date : date
  * <color:#336791><b>rank_code</b></color> : varchar <<FK -> ACADEMIC_RANK>>
}

entity PROF_SPECIALIZATION {
  * <color:#9b59b6><b>person_id</b></color> : int <<PK, FK -> PROFESSOR>>
  * <color:#9b59b6><b>specialization</b></color> : varchar <<PK>>
  --
}

entity STUDENT {
  * <color:#9b59b6><b>person_id</b></color> : int <<PK, FK -> PERSON>>
  --
  * student_id : varchar <<UK>>
  * admission_date : date
    gpa : numeric
  * academic_standing : varchar
}

entity STUDENT_DEGREE {
  * <color:#9b59b6><b>person_id</b></color> : int <<PK, FK -> STUDENT>>
  * <color:#9b59b6><b>degree_type</b></color> : varchar <<PK>>
  * <color:#9b59b6><b>institution</b></color> : varchar <<PK>>
  --
    year : int
}

PERSON ||--o{ PERSON_PHONE : "phone_numbers"
PERSON ||--o{ PERSON_EMAIL : "email_addresses"
PROFESSOR ||--o{ PROF_SPECIALIZATION : "specializations"
STUDENT ||--o{ STUDENT_DEGREE : "previous_degrees"
@enduml
'-------------------------
' DARK
'-------------------------
@startuml
!theme blueprint
hide circle
skinparam linetype ortho
skinparam defaultFontName Arial

entity GRAD_STUDENT {
  * <color:#EECBFF><b>person_id</b></color> : int <<PK, FK -> STUDENT>>
  --
    thesis_topic : varchar
}

entity PROFESSOR {
  * <color:#EECBFF><b>person_id</b></color> : int <<PK, FK -> PERSON>>
  --
  * professor_id : varchar <<UK>>
    salary : numeric
  * hire_date : date
  * <color:#E6EDF9><b>rank_code</b></color> : varchar <<FK -> ACADEMIC_RANK>>
}

entity COURSE_SECTION {
  * <color:#EECBFF><b>course_id</b></color> : varchar <<PK, FK -> COURSE>>
  * <color:#EECBFF><b>section_no</b></color> : varchar <<PK (partial key)>>
  --
    semester : varchar
    year : int
    capacity : int
    schedule : varchar
}

entity TA_ASSIGNMENT {
  * <color:#EECBFF><b>course_id</b></color> : varchar <<PK, FK -> COURSE_SECTION>>
  * <color:#EECBFF><b>section_no</b></color> : varchar <<PK, FK -> COURSE_SECTION>>
  --
  * <color:#E6EDF9><b>grad_person_id</b></color> : int <<FK -> GRAD_STUDENT>>
  * <color:#E6EDF9><b>professor_person_id</b></color> : int <<FK -> PROFESSOR>>
}

COURSE_SECTION ||--o| TA_ASSIGNMENT : "ta_assign"
GRAD_STUDENT ||--o{ TA_ASSIGNMENT : "assigned_as_ta"
PROFESSOR ||--o{ TA_ASSIGNMENT : "supervises"
@enduml